server:
  port: 8082

spring:
  application:
    name: song-service

  datasource:
    url: jdbc:postgresql://localhost:5434/song_service_db
    username: song_user
    password: song_pass
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true