CREATE TABLE IF NOT EXISTS resources (
                                         id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                                         data BYTEA NOT NULL,
                                         PRIMARY KEY (id)
    );