server:
  port: 8081

spring:
  application:
    name: resource-service

  datasource:
    url: jdbc:postgresql://localhost:5433/resource_service_db
    username: resource_user
    password: resource_pass
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

song-service:
  url: http://localhost:8082